# Generated by Praetor from declared project commands; execution is unverified.
.PHONY: all verify-all compile-context compile-context-verify audit build test

all: build

verify-all: compile-context-verify audit test

compile-context:
	@standardsctl compile-context

compile-context-verify:
	@standardsctl compile-context --verify

audit:
	@standardsctl audit

test: build
	@'npm' 'run' 'check'
	@'npm' 'run' 'test'

build:
	@'npm' 'run' 'build'
