# Generated by Praetor from declared project commands; execution is unverified.
# Praetor ships one binary under two names; resolve whichever is installed.
PRAETORCTL ?= $(shell command -v praetorctl 2>/dev/null || command -v standardsctl 2>/dev/null || echo praetorctl)
.PHONY: all verify-all compile-context compile-context-verify audit build test

all: build

verify-all: compile-context-verify audit test

compile-context:
	@$(PRAETORCTL) compile-context

compile-context-verify:
	@$(PRAETORCTL) compile-context --verify

audit:
	@$(PRAETORCTL) audit

test: build
	@exec 'npm' 'run' 'check'
	@exec 'npm' 'run' 'test'

build:
	@exec 'npm' 'run' 'build'
